### ISSUE TITLE
fix view store page and game page

### ISSUE THREAD

**Issue by gubanovpm** [GrassKhoPper/database_hw#16]
![image](https://github.com/user-attachments/assets/e2197e18-b00d-4d88-9fb5-4beadb5e0aed)

картинки имеют разные размеры ( авторазмер какой-то ненормированный ) и выстраиваются в колонки, а не строки
возможно, представление было поломано при изменении html вставками jinja2

**Comment by IvanKhrol** [comment]
Пофиксил баг отображения, а также в общем улучшил отображения при изменении разрешения экрана
