### ISSUE TITLE
Add 400 error page html file design

### ISSUE THREAD

**Issue by gubanovpm** [GrassKhoPper/database_hw#28]

**Comment by IvanKhrol** [comment]
Добавил template для страницы ошибки
Ветка [error_page](https://github.com/GrassKhoPper/database_hw/tree/error_page)
[Коммит](https://github.com/GrassKhoPper/database_hw/commit/efff4b4954ff4f51e88da4426a92360bbf2ce01a)

**Comment by gubanovpm** [comment]
https://github.com/GrassKhoPper/database_hw/pull/60
